version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Running tests"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
