version: 0.2

phases:
  install:
    runtime-versions:
    
      python: 3.8  # Specify the Python version you want to use
    commands:
      - echo "Installing dependencies (if any)"
      - pip install --upgrade pip
  build:
    commands:
      - echo "Running tests"

      - echo "Running newfile.py"
      - python newfile.py

artifacts:
  files:
    - '**/*'
  discard-paths: yes
